# Configuration for PR auto-labeling based on file paths
# See: https://github.com/actions/labeler

# Components
'component':
    - changed-files:
          - any-glob-to-any-file: 'src/components/**/*'

# Hooks
'hooks':
    - changed-files:
          - any-glob-to-any-file: 'src/hooks/**/*'

# Adapters
'adapters':
    - changed-files:
          - any-glob-to-any-file: 'src/adapters/**/*'

# Queries
'queries':
    - changed-files:
          - any-glob-to-any-file: 'src/queries/**/*'

# Providers
'providers':
    - changed-files:
          - any-glob-to-any-file: 'src/providers/**/*'

# Styles
'styling':
    - changed-files:
          - any-glob-to-any-file:
                - 'src/styles/**/*'
                - '**/*.css'
                - '**/*.scss'
                - '**/*.module.css'

# Configuration
'config':
    - changed-files:
          - any-glob-to-any-file:
                - '*.json'
                - '*.yml'
                - '*.yaml'
                - '.github/**/*'
                - 'tsconfig.json'
                - 'next.config.*'

# Documentation
'documentation':
    - changed-files:
          - any-glob-to-any-file:
                - '**/*.md'
                - 'docs/**/*'

# Tests
'tests':
    - changed-files:
          - any-glob-to-any-file:
                - '**/*.test.ts'
                - '**/*.test.tsx'
                - '**/*.spec.ts'
                - '**/*.spec.tsx'
                - 'tests/**/*'

# CI/CD
'ci':
    - changed-files:
          - any-glob-to-any-file: '.github/workflows/**/*'

# Dependencies
'dependencies':
    - changed-files:
          - any-glob-to-any-file:
                - 'package.json'
                - 'pnpm-lock.yaml'
                - 'package-lock.json'
                - 'yarn.lock'

'feature':
      - head-branch: ['^feature', 'feat']

'bugfix':
      - head-branch: ['^fix', 'bugfix', 'hotfix']

'release':
      - head-branch: ['^release']